### PR TITLE
implement Tag deserialization

### PR DESCRIPTION
**Pull request by Giszmo**

### CODE REVIEW

**Comment by Giszmo** [comment]
That said, your Tag class has a third val: `recommendedRelayUrl: String? = null` which I am not familiar with and ignored in my PR so far. Can Tag arrays be 3-long with this, too? I can add it as third parameter in that way if you agree it is necessary but for now I am curious to learn if that test that failed here does fail for you, too.

**Comment by AnonymousGeekDev** [comment]
@Giszmo Yeah the 3rd parameter is important. It is mentioned as optional in the Nostr specs.

**Comment by AnonymousGeekDev** [comment]
Yeah, the default does not work. Anyway, when the mentioned bug in Jackson-kotlin is solved, we will probably get rid of the custom serializer/deserializer :-)

**Comment by Giszmo** [comment]
In my nostr library I now went with tags being just a `List<List<String>>` as nip1 doesn't limit the length of the inner list and some events have 4 elements already. Guess Tags needs sub-classes for all kinds of Tags.

**Pull request merged**
