### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by Giszmo**
remove empty proguard rules
remove junit4
remove null-checks on non-nullable variables
move test classes into correct packages
move test_subscriptions_data to resources/

### CODE REVIEW

**Comment by AnonymousGeekDev** [comment]
Thanks @Giszmo .

**Comment by AnonymousGeekDev** [comment]
As for the checks in CryptoUtils, I put them there as an extra check for the stuff those functions handle.

**Comment by Giszmo** [comment]
Take what you want.

Kotlin is null-safe. Testing a non-nullable variable for being null makes no sense in Kotlin. AndroidStudio also shows you those instances and it makes those extra lines of code all the more distracting.

ProGuard ... well, I hate it but right now it's dead code and thus only distraction.

I was about to abandon your project due to the constant weird crash every time I was running

```
$ ./gradlew clean :kostr-core:test
```

but right now, if I comment out `ktnostr.nostr.NostrTests.it can correctly parse a received event`, it works fine, so maybe I finally look into what your lib actually does or does not provide, after so far only having cleaned up stuff that wasn't "industry standard".

**Comment by AnonymousGeekDev** [comment]
I see.

**Comment by AnonymousGeekDev** [comment]
@Giszmo I made that should probably fix the issue for that test. Also, please redirect this change to the 'develop' branch.

**Pull request merged**
